controllers:
    resource:
        path: ../UI/Http/Rest/Controller
        namespace: UI\Http\Rest\Controller\
    type: attribute

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }